---
  - name: "breaking-change"
    color: ee0701
    description: "A change that breaks backward compatibility for tests or APIs."

  - name: "test-fix"
    color: ee0701
    description: "Fixes for inconsistent or failing tests."

  - name: "test-improvement"
    color: 1d76db
    description: "Improvements to existing tests, not introducing new features."

  - name: "new-test"
    color: 0e8a16
    description: "New tests or test scenarios."

  - name: "test-refactor"
    color: 1d76db
    description: "Updating test code with simpler, easier to understand or more efficient syntax or methods."

  - name: "test-performance"
    color: 1d76db
    description: "Improving performance of tests, not introducing new features."

  - name: "selenium-update"
    color: 1d76db
    description: "Updates to Selenium dependencies or versions."

  - name: "csharp-update"
    color: 1d76db
    description: "Updates to C# language or .NET framework."

  - name: "specflow-update"
    color: 1d76db
    description: "Updates to SpecFlow dependencies or versions."

  - name: "ci-improvement"
    color: 1d76db
    description: "Work that improves the continuous integration for tests."

  - name: "test-data-update"
    color: 1d76db
    description: "Updates to test data or fixtures."

  - name: "in-progress"
    color: fbca04
    description: "Issue is currently being worked on by a developer."

  - name: "stale"
    color: fef2c0
    description: "No activity for quite some time."

  - name: "no-stale"
    color: fef2c0
    description: "This is exempt from the stale bot."

  - name: "security"
    color: ee0701
    description: "Addressing a vulnerability or security risk in tests or APIs."

  - name: "incomplete"
    color: fef2c0
    description: "Missing information or context for tests."

  - name: "invalid"
    color: fef2c0
    description: "This is off-topic, spam, or otherwise doesn't apply to this project."

  - name: "beginner-friendly"
    color: 0e8a16
    description: "Good first issue for people wanting to contribute to this project."

  - name: "help-wanted"
    color: 0e8a16
    description: "We need some extra helping hands or expertise in order to resolve this!"

  - name: "priority-critical"
    color: ee0701
    description: "Must be addressed as soon as possible to prevent test failures."

  - name: "priority-high"
    color: b60205
    description: "After critical issues are fixed, these should be dealt with before any further issues."

  - name: "priority-medium"
    color: 0e8a16
    description: "This issue may be useful, and needs some attention to improve tests."

  - name: "priority-low"
    color: e4ea8a
    description: "Nice addition, maybe... someday... to improve tests."